a=int(input("Enter a number: "))
b=int(input("Enter another number: "))

print("The addition of",a, "and",b, "is:",(a+b))
print("The difference between",a, "and",b, "is: ",(a-b))
print("The multiplication of",a,"and",b,"is:",(a*b))
print("The division of", a,"and",b,"is:",(a/b))
print("The exponential of",a,"and",b,"is:",(a**b))
print("The remainder comes out to be:",(a%b))
print("Floor division operator",a,"and",b,"is:",(a//b))